main/main.cpp, main/modules/bluetooth.cpp, main/modules/expander.cpp, main/modules/module.cpp, main/modules/module.h, main/modules/proxy.cpp, main/modules/proxy.h
This PR allows _writing_ properties for modules that run on an expander. Until now these values haven't been forwarded, so the change was ineffective. Now they are sent to the expander over serial.
In order to avoid endless loops of back and forth, we have to consider whether a property value originates from the expander (then we don't need to send it back) or from another source like user or bluetooth (then we need to send it to the expander).
=> Forward property values from proxy module to expander

docs/module_reference.md, main/modules/input.h, main/modules/module.cpp, main/modules/module.h, main/modules/motor_axis.cpp, main/modules/motor_axis.h, main/modules/stepper_motor.cpp, main/modules/stepper_motor.h
The main goal of this module is to quickly respond to switches and protect the hardware from damage - even if, for example, no RoSys is running, a different serial interface is being used, or a developer sends "manual" commands via the Lizard console.
Tasks:
Maybe later:
=> Implement new MotorAxis module

docs/module_reference.md, main/modules/module.cpp, main/modules/odrive_motor.cpp, main/modules/odrive_motor.h
Ad a function, where the Odrive module now supports the heartbeat message of the Motor axis. If the firmware version of the Odrive is `0.5.6` the hearbeat will return a `motor_error_flag`. The version can be given as a third variable(for example `m = ODriveMotor(can, 0x100,6)` , when caling the constructor of the OdriveMotor. When no version is given, version `0.5.4` will be used. This can be reset using the reset_motor() function. After this the motor will work again. this reset works for both firmware versions, but only `0.5.6`will give feedback.
=> Odrive error handling

main/storage.cpp
Hello,
As of now there is no exact explanation for when the storage module failed to write to flash.
In order to be able to differentiate between different failure modes, the error message includes the esp_err_t string in the sotrage class.
=> More information on storage failure

docs/module_reference.md, main/modules/rmd_motor.cpp, main/modules/rmd_motor.h, main/modules/rmd_pair.cpp
This PR uses commands 0x92 and 0x9C again for RMD motors to keep speed, torque and temperatures updated.
It also avoids RMD motor pairs running out of sync due to communication errors with one of them.
=> Re-introduce RMD properties (speed, torque, temperature) and improve RMD pair synchronization

docs/module_reference.md, main/modules/expander.cpp, main/modules/module.cpp
I've changed the expander, so I can run without a boot and enable pin set. You can't use `expander.flash()` anymore, but the rest of the functionality is the same.
---
Feature request: #54
=> Expander with 2 Pins

main/utils/serial-replicator.cpp
Updated the `expander.flash()` functionality to work with OTA.
Tested in all 4 possible active ota partition combinations.
---
Issue: #53
=> Expander flash() working again.

docs/module_reference.md, main/modules/expander.cpp, main/modules/expander.h
Hello,
This change enables one to write rules or higher level controls which are dependent on wether or not the expander actually transmits data.
This could be used for motor-movement based on sensor data from a sensor on an expander, where communication could fail or is highly time-critical.
=> Expander last_message_age property.

flash.py
The manual size validation is removed and is fully handled by ```--flash_size detect```, that is already added the esptool.py.
In some cases, the esptool.py flash_id call could not connect to the esp32, even if the flashing worked. For example, with the Zauberzeug Robotbrain.
=> Remove size validation

main/modules/serial.cpp
This is a fix for #86.
Size_t is unsigned and pos can be negative. After the change, I could not reproduce the problem.
Also, I increased the size of the patter queue to 100, like in the main queue with uart 0. I ran into a full queue multiple times.
`W (3232) uart: Fail to enqueue pattern position, pattern queue is full.`
=> Buffer comparison cast fix

main/modules/core.cpp, main/modules/expander.cpp, main/modules/expander.h, main/modules/proxy.cpp, main/modules/proxy.h
This will handle the 2nd update from the #18.  With this change, the expander module will be able to detect a crash within the expander esp32. It will then unready itself until the expander esp32 is responding again.
Also, the handling of proxies is changed. Proxy initialization is tied to the expander module's state, and the proxy itself will update its ready flag based on the expander.
=> Expander improvements II

docs/module_reference.md, main/modules/expander.cpp, main/modules/expander.h
This is for #75
----
Before flashing, the p0.flash() call will set the GPIO0 to the correct state and check GPIO2 and GPIO12 on the p0 for their states. 
GPIO0 and 2 are responsible for booting to the bootloader upon restart. 
GPIO12 on low sets the flash voltage to 3.3V. On high, which sets it to 1.8V, it can cause issues when flashing.
The strapping register itself does not need to be checked in that stage of flashing. Since the configuration after the restart would be the relevant one, but then the p0 would be in bootloader mode, which we would not have to check and could not check.
=> Check relevant pins for p0.flash()

main/modules/expander.cpp, main/modules/serial.cpp, main/modules/serial.h
This is a fix mainly for #96. Yet this turned out to be more of an Expander Improvements III.
With the uart being handled properly after the flashing, it stops spamming the uart error.
Since it turned out to be more of an Expander Improvements III, I also added the missing `this->` to the code.
The flashing is very solid now, I tried to make it fail and did not manage to do so.
=> Expander Improvements III (Uart spam fix)

main/modules/expander.cpp, main/modules/expander.h, main/modules/proxy.cpp
This adds the ability for the expander module to set expressions even if the expander esp is not ready yet. It will restore them on reboot as well.
=> Proxy persistent property handling

gen_parser.sh, main/parser.h
This is a fix for #24 
Test outputs:
```
> core.print('boo\nbobobobobob')
"boo
bobobobobob"
> core.print('rbnr\nt')
"rbnr
t"
> core.print('boo\n')
"boo
"
```
No characters were lost in printing
=> Fix escape character handling in parser.h

.github/workflows/release.yml, gen_parser.sh, main/CMakeLists.txt, main/parser.h
This updates owl to the current main version without the need for any hotfixes.
=> Update owl without hotfixes

esp.py, flash.py
When debugging some Hardware Problems, we noticed, that enabel resets the ESP and does not simply enable it. To fix this I added a new enable function to the flash script and changed the enable function to reset. 
This should fix the confusion of the naming.
=> fix reset and enable confusion

sdkconfig.defaults
This fixes an older bug in the twai driver. It disables the [SW workaround for TX interrupt lost errata](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html#config-twai-errata-fix-tx-intr-lost). 
Testet on robot for almost 15 hours without crash.
Disabling CONFIG_TWAI_ERRATA_FIX_TX_INTR_LOST may lead to lost transmit interrupts, affecting message transmission reliability. A fix was not implemented yet and only mentioned in this [thread](https://github.com/espressif/esp-idf/issues/9697). I also asked what the status is on this.
=> Add a workaround for a bug in the TWAI driver

main/modules/can.cpp
The documentation mentions `can.get_status()`, but the implementation checks for `can.status()`. This PR changes the implementation to check for `can.get_status()` because this is a better name for a method. Since this method is probably rarely used, the breaking change shouldn't be a problem.
=> Fix mismatch between `can.status()` and `can.get_status()`

docs/module_reference.md, main/modules/imu.cpp, main/modules/imu.h
This PR allows to access more properties (calibration, acceleration, magnetometer, gyroscope, Euler/quaternion orientation, linear acceleration, gravity, temperature) and to change the operation mode.
Open tasks:
The latter is an idea to reduce the I2C traffic. If the operation mode is GYROONLY, it doesn't make too much sense to fetch acceleration data.
But on the other hand, it might still be useful to fetch orientation data, even though the datasheet says such fused data isn't available in non-fusion modes. Empirically it looks like orientation data is still provided and would be useful to avoid the need to integrate angular velocities on the host system.
=> Add more IMU properties and allow setting the operation mode

docs/module_reference.md, main/modules/dunker_motor.cpp
This PR adds properties "voltage_logic" and "voltage_power" as well as the method "update_voltages()" to the DunkerMotor module. I couldn't manage to setup TPDOs to automatically update voltages in a fixed interval, so I decided to leave it up to the user to update them on demand.
=> Allow reading voltages from dunker motors

.syncignore, esp.py, flash.py
The esp class already supports enabling and resetting the microcontroller, this adds functionality to disable it.
This will be used in a future security feature to shut the microcontroller down, when it doesn't respond anymore.
After it's disabled, it needs to be reset to get running again; not to be enabled.
=> Add disable function to esp class

.github/zip_content.txt, .vscode/settings.json, docs/getting_started.md, docs/tools.md, esp.py, espresso.py, flash.py
This PR introduces a new script to flash and configure an ESP microcontroller from a Jetson computer inside a Zauberzeug Robot Brain. It uses argparse to define a clean command line API. In order to avoid breaking changes with downstream libraries like RoSys, we decided to start a new script next to flash.py, which we can deprecate (and remove in Lizard 1.0).
The script comes with a `-d` or `--dry-run` option to test it without a Robot Brain:
```bash
./espresso.py --help
./espresso.py flash -j nano -d /dev/foo
```
We chose argparse over Typer to avoid an extra dependency (which can be cumbersome in robotics projects).
@pascalzauberzeug will test the new script on Monday. Everyone else is invited to share thoughts and opinions.
We plan to release it in version 0.7.1, even though it is …
=> Introduce espresso.py to replace flash.py in the future

main/modules/stepper_motor.cpp
The stepper motor did not calculate its `remaining_distance` to the target correctly and did not stop.
Now it correctly stops when `remaining_distance < braking_distance`.
=> Fix braking for position control of the stepper motor

main/main.cpp
Fixed a crash that occurred when resetting the ESP while it was connected over serial. The UART now has a proper queue to handle incoming data during boot, preventing interrupt crashes.
The issue manifested as a boot loop with the following error when connected via serial:
`assert failed: xQueueGenericSendFromISR queue.c:1180 (pxQueue)`
I noticed the fail with RoSys and Basekit.
=> Add UART queue to prevent reset crashes
